version: '3.5'

services:

  mock-client:
    build: ./mock-client
    restart: always
    networks:
      - webnet
    volumes:
      - ./mock-client:/mock-client

  mock-backend:
    build: ./mock-backend
    restart: always
    networks:
      - webnet
    volumes:
      - ./mock-backend:/mock-backend

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - mock-client
      - mock-backend
    networks:
      - webnet
    ports:
      - 3000:80
    
networks:

  webnet:
